# Generated by Django 4.1.7 on 2023-06-30 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_bookstore_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='store.bookstore'),
        ),
    ]
